name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Utiliza tu runner auto-hospedado en EC2

    strategy:
      matrix:
        node-version: [20.x]  # Versión de Node recomendada

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'  # Usa cache para yarn

      - name: Install Yarn
        run: |
          npm install -g yarn  # Instala Yarn globalmente

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build  # Asegúrate de que este script existe en package.json
