name: Node.js CI

on:
  push:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Clean Yarn cache
        run: yarn cache clean

      - name: Clean APT cache
        run: |
          sudo apt-get clean
          sudo apt-get autoclean

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@ec2-18-144-70-160.us-west-1.compute.amazonaws.com << EOF
            cd /home/ubuntu/_work/Front-App/Front-App
            git pull origin main
            yarn install
            yarn build
            sudo systemctl restart nginx
          EOF
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
