name: Node.js CI  

on:
  push:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4  

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'  

      - name: Clean Yarn cache
        run: yarn cache clean  

      - name: Clean APT cache
        run: |
          sudo apt-get clean  
          sudo apt-get autoclean 

      - name: Install Yarn
        run: |
          npm install -g yarn  # Instala Yarn globalmente

      - name: Install dependencies
        run: yarn install  # Instala las dependencias del proyecto

      - name: Build the project
        run: yarn build

      - name: Build the project
        run: yarn build  # Compila o construye el proyecto
